input_max_length: 8192
datasets: alce_asqa_30
generation_max_length: 300
test_files: data/alce/asqa_eval_gtr_top2000.json
demo_files: prompts/asqa_revised.json
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
