input_max_length: 16384,16384,16384,16384,16384
datasets: icl_trec_coarse_800shot_balance,icl_trec_fine_800shot_balance,icl_banking77_720shot_balance,icl_clinic150_880shot_balance,icl_nlu_1020shot_balance
generation_max_length: 20,20,20,20,20
test_files: ',,,,'
demo_files: ',,,,'
use_chat_template: false
max_test_samples: 500
shots: 0
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
