input_max_length: 32768,32768
datasets: icl_banking77_1450shot_balance,icl_clinic150_1750shot_balance
generation_max_length: 20,20
test_files: ','
demo_files: ','
use_chat_template: false
max_test_samples: 500
shots: 0
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
