input_max_length: 32768,32768,32768
datasets: narrativeqa_32468,infbench_qa_eng_32558,infbench_choice_eng_32558
generation_max_length: 100,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
