input_max_length: 16384
datasets: kilt_popqa_3
generation_max_length: 128
test_files: data/kilt/popqa_test_1000_k105_dep6.jsonl
demo_files: data/kilt/popqa_test_1000_k3_dep6.jsonl
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: true
model_name_or_path: /scratch/gpfs/DANQIC/models/Qwen2.5-7B