input_max_length: 32768
datasets: kilt_nq
generation_max_length: 128
test_files: data/kilt/nq-dev-multikilt_1000_k220_dep6.jsonl
demo_files: data/kilt/nq-train-multikilt_1000_k3_dep6.jsonl
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: true
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct