input_max_length: 16384
datasets: json_kv
generation_max_length: 100
test_files: data/json_kv/test_k220_dep6.jsonl
demo_files: ''
use_chat_template: false
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
