input_max_length: 8192,8192
datasets: infbench_sum_eng_6792,multi_lexsum_7492
generation_max_length: 1200,400
test_files: ','
demo_files: ','
use_chat_template: true
max_test_samples: 100
shots: 2
stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
